# Generated by Django 2.1.1 on 2018-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwmac', '0002_auto_20181001_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
